import uuid
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.deps import get_current_user, RoleChecker
from app.crud import visitors as crud_visitors
from app.models.users import User, Flat
from app.schemas.visitors import (
    VisitorPassOut,
    VisitorPassCreate,
    VisitorLogOut,
    VisitorLogCreate,
    DailyHelpOut,
    DailyHelpCreate,
    DailyHelpCreateByResident,
)

router = APIRouter()

# Role checkers
security_or_admin = RoleChecker(["security", "admin"])
admin_required = RoleChecker(["admin"])


@router.post("/pre-approve", response_model=VisitorPassOut)
async def pre_approve_visitor(
    payload: VisitorPassCreate, 
    db: AsyncSession = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Generate a pre-approved visitor pass. Accessible by residents and tenants."""
    # Verify resident lives in the flat
    flat_query = select(Flat).where(Flat.id == payload.flat_id)
    flat_res = await db.execute(flat_query)
    flat = flat_res.scalar_one_or_none()
    
    if not flat:
        raise HTTPException(status_code=404, detail="Flat not found")
        
    if current_user.role not in ["admin"] and flat.owner_id != current_user.id and flat.tenant_id != current_user.id:
        raise HTTPException(
            status_code=403,
            detail="You can only pre-approve visitors for flats where you reside",
        )
        
    return await crud_visitors.create_visitor_pass(db, payload, current_user.id)


@router.get("/my-passes", response_model=List[VisitorPassOut])
async def get_my_passes(
    limit: int = 100,
    offset: int = 0,
    db: AsyncSession = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """Retrieve visitor passes generated by the current resident."""
    return await crud_visitors.get_visitor_passes_by_resident(db, current_user.id, limit=limit, offset=offset)


@router.post("/gate/check-in", response_model=VisitorLogOut, dependencies=[Depends(security_or_admin)])
async def gate_check_in(
    payload: VisitorLogCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Log entry at the gate.
    Can verify a passcode (6-digit visitor OTP or daily help pass) or record a manual walk-in.
    Accessible by security guards and admins.
    """
    log = await crud_visitors.log_visitor_entry(db, payload, current_user.id)
    if not log:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid passcode or missing details for manual entry",
        )
    return log


@router.post("/gate/check-out/{log_id}", response_model=VisitorLogOut, dependencies=[Depends(security_or_admin)])
async def gate_check_out(
    log_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Record visitor departure at the gate. Accessible by security guards and admins."""
    log = await crud_visitors.log_visitor_exit(db, log_id, current_user.id)
    if not log:
        raise HTTPException(
            status_code=404,
            detail="Active entry log not found or already checked out",
        )
    return log


@router.get("/gate/active", response_model=List[VisitorLogOut], dependencies=[Depends(security_or_admin)])
async def view_active_visitors(
    limit: int = 100,
    offset: int = 0,
    db: AsyncSession = Depends(get_db)
):
    """Get list of all visitors currently inside the society. Accessible by security guards/admins."""
    return await crud_visitors.get_active_gate_logs(db, limit=limit, offset=offset)


@router.get("/gate/history", response_model=List[VisitorLogOut], dependencies=[Depends(security_or_admin)])
async def view_visitor_history(
    limit: int = 100,
    offset: int = 0,
    db: AsyncSession = Depends(get_db)
):
    """Get chronological log of all gate movements. Accessible by security guards/admins."""
    return await crud_visitors.get_gate_logs_history(db, limit=limit, offset=offset)


@router.post("/daily-help", response_model=DailyHelpOut, dependencies=[Depends(admin_required)])
async def register_daily_help(payload: DailyHelpCreate, db: AsyncSession = Depends(get_db)):
    """Register daily help staff (maid, driver) and link to flats. Admin only."""
    # Verify all flat IDs exist
    for f_id in payload.flat_ids:
        flat_res = await db.execute(select(Flat).where(Flat.id == f_id))
        if not flat_res.scalar_one_or_none():
            raise HTTPException(status_code=400, detail=f"Flat {f_id} does not exist")
            
    db_help = await crud_visitors.create_daily_help(db, payload)
    
    # Return schema out format
    return {
        "id": db_help.id,
        "name": db_help.name,
        "phone": db_help.phone,
        "role": db_help.role,
        "pass_code": db_help.pass_code,
        "is_active": db_help.is_active,
        "created_at": db_help.created_at,
        "flats": [f"{f.block}-{f.flat_number}" for f in db_help.flats]
    }


@router.get("/daily-help", response_model=List[DailyHelpOut])
async def list_daily_help(
    limit: int = 100,
    offset: int = 0,
    db: AsyncSession = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    """List registered daily help workers. Accessible by all authenticated users."""
    helps = await crud_visitors.get_all_daily_helps(db, limit=limit, offset=offset)
    out = []
    for h in helps:
        out.append({
            "id": h.id,
            "name": h.name,
            "phone": h.phone,
            "role": h.role,
            "pass_code": h.pass_code,
            "is_active": h.is_active,
            "created_at": h.created_at,
            "flats": [f"{f.block}-{f.flat_number}" for f in h.flats]
        })
    return out


@router.post("/daily-help/register-by-resident", response_model=DailyHelpOut)
async def register_daily_help_by_resident(
    payload: DailyHelpCreateByResident,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Register daily help staff (maid, driver) and link to resident's flat."""
    from sqlalchemy import or_
    
    # Find resident's flat
    flat_res = await db.execute(
        select(Flat).where(or_(Flat.owner_id == current_user.id, Flat.tenant_id == current_user.id))
    )
    flat = flat_res.scalars().first()
    if not flat:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="You must be associated with a flat to register daily help",
        )
    
    # Convert to DailyHelpCreate schema
    create_payload = DailyHelpCreate(
        name=payload.name,
        phone=payload.phone,
        role=payload.role,
        flat_ids=[flat.id]
    )
    
    db_help = await crud_visitors.create_daily_help(db, create_payload)
    return {
        "id": db_help.id,
        "name": db_help.name,
        "phone": db_help.phone,
        "role": db_help.role,
        "pass_code": db_help.pass_code,
        "is_active": db_help.is_active,
        "created_at": db_help.created_at,
        "flats": [f"{f.block}-{f.flat_number}" for f in db_help.flats]
    }


@router.post("/daily-help/{help_id}/link", response_model=DailyHelpOut)
async def link_daily_help_to_flat(
    help_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Link an existing daily helper to the resident's flat."""
    from sqlalchemy import or_
    from app.models.visitors import DailyHelp, DailyHelpFlat
    
    # Find helper
    help_res = await db.execute(select(DailyHelp).where(DailyHelp.id == help_id))
    db_help = help_res.scalar_one_or_none()
    if not db_help:
        raise HTTPException(status_code=404, detail="Daily help not found")
        
    # Find flat
    flat_res = await db.execute(
        select(Flat).where(or_(Flat.owner_id == current_user.id, Flat.tenant_id == current_user.id))
    )
    flat = flat_res.scalars().first()
    if not flat:
        raise HTTPException(status_code=400, detail="No flat associated with your profile")
        
    # Check if already linked
    existing = await db.execute(
        select(DailyHelpFlat).where(
            DailyHelpFlat.daily_help_id == help_id,
            DailyHelpFlat.flat_id == flat.id
        )
    )
    if not existing.scalar_one_or_none():
        association = DailyHelpFlat(daily_help_id=help_id, flat_id=flat.id)
        db.add(association)
        await db.commit()
        
    # Refresh and return
    await db.refresh(db_help, ["flats"])
    return {
        "id": db_help.id,
        "name": db_help.name,
        "phone": db_help.phone,
        "role": db_help.role,
        "pass_code": db_help.pass_code,
        "is_active": db_help.is_active,
        "created_at": db_help.created_at,
        "flats": [f"{f.block}-{f.flat_number}" for f in db_help.flats]
    }


@router.post("/daily-help/{help_id}/unlink", response_model=DailyHelpOut)
async def unlink_daily_help_from_flat(
    help_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Unlink a daily helper from the resident's flat."""
    from sqlalchemy import or_
    from app.models.visitors import DailyHelp, DailyHelpFlat
    
    # Find helper
    help_res = await db.execute(select(DailyHelp).where(DailyHelp.id == help_id))
    db_help = help_res.scalar_one_or_none()
    if not db_help:
        raise HTTPException(status_code=404, detail="Daily help not found")
        
    # Find flat
    flat_res = await db.execute(
        select(Flat).where(or_(Flat.owner_id == current_user.id, Flat.tenant_id == current_user.id))
    )
    flat = flat_res.scalars().first()
    if not flat:
        raise HTTPException(status_code=400, detail="No flat associated with your profile")
        
    # Delete association
    assoc_res = await db.execute(
        select(DailyHelpFlat).where(
            DailyHelpFlat.daily_help_id == help_id,
            DailyHelpFlat.flat_id == flat.id
        )
    )
    association = assoc_res.scalar_one_or_none()
    if association:
        await db.delete(association)
        await db.commit()
        
    # Refresh and return
    await db.refresh(db_help, ["flats"])
    return {
        "id": db_help.id,
        "name": db_help.name,
        "phone": db_help.phone,
        "role": db_help.role,
        "pass_code": db_help.pass_code,
        "is_active": db_help.is_active,
        "created_at": db_help.created_at,
        "flats": [f"{f.block}-{f.flat_number}" for f in db_help.flats]
    }

